version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .  # Install dependencies
  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r lambda_function.zip .  # Create the deployment package
  post_build:
    commands:
      - echo "Build complete"
artifacts:
  files:
    - lambda_function.zip
